const baseUrl = import.meta.env.VITE_API_URL
export const postMethod = 'POST'
export const getMethod = 'GET'
export const deleteMethod = 'DELETE'
export const putMethod = 'PUT'
export const createAccountUrl = `${baseUrl}/api/user/add`
export const createRoomUrl = `${baseUrl}/api/chat-room/create`
export const destroyRoomUrl = `${baseUrl}/api/chat-room/destroy`
export const joinRoomUrl = `${baseUrl}/api/auth/join`
export const leaveRoomUrl = `${baseUrl}/api/auth/leave`
export const isAuthUrl = `${baseUrl}/api/auth/is-auth`
export const getMessagesUrl = `${baseUrl}/api/messages/get-messages`
export const updateUserUrl = `${baseUrl}/api/user/update`
